yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls',namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models

# Create your models here.

yatube/posts/views.py
from django.shortcuts import render

from django.http import HttpResponse

from django.shortcuts import render
# Главная страница
#def index(request):    
    #return HttpResponse('Главная страница')



def index(request):
    template = 'posts/index.html'
    
    # Словарь с данными принято называть context
    context = {
        # В словарь можно передать переменную
        
        # А можно сразу записать значение в словарь. Но обычно так не делают
        'text': 'Это главная страница проекта Yatube',
    }
    return render(request, template, context) 


def group_posts(request, slug):
    template = 'posts/group_list.html'
    context = {
        # В словарь можно передать переменную
        
        # А можно сразу записать значение в словарь. Но обычно так не делают
        'text': 'Здесь будет информация о группах проекта Yatube',
    }
    return render(request, template, context) 
    
    

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    
    <title>
      {% block title %}
        титла нет :(
      {% endblock %}

    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %} 
    </header>
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        {% block content %}
        Контент не подвезли :(
        {% endblock %}

       </div>  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отсупом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
      
        <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
      

yatube/templates/includes/header.html
      {% load static %}

      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

      {% load static %} 
      
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <!-- ссылка должна вести на главную страницу -->
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <!--<img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">-->
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>


      

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block title %}
  Записи сообщества
  {% endblock %}
  {% block content %}
  {{ text }}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последнее обновление на сайте
{% endblock %}
{% block content %}
  {{ text }}
{% endblock %} 